# Generated by Django 5.0.1 on 2024-01-25 08:10

import django.db.models.deletion
import src.funks
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('domain', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(default=src.funks.gen_secret, max_length=255)),  # noqa
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),  # noqa
            ],
        ),
    ]
