name: Docker Build and Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push multi-arch Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/demos:latest \
            .

      - name: Pull Docker image on remote server and restart container
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            docker rm -f demos || true && \
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/demos:latest || true && \
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demos:latest && \
            docker run -d \
              --name demos \
              -p 127.0.0.1:18443:80 \
              -p 0.0.0.0:2222:22 \
              -v /srv/demos/db.sqlite3:/srv/demos/db.sqlite3 \
              -v /srv/demos/.env:/srv/demos/.env \
              -v /srv/demos/nginx/logs:/var/log/nginx \
              -v /srv/demos/logs:/srv/demos/logs \
              ${{ secrets.DOCKERHUB_USERNAME }}/demos:latest && \
            docker exec demos python manage.py migrate && \
            docker exec demos python manage.py generate_config
          '
